"""Web Application for Find By Color Proof of Concept"""

import os
import streamlit as st
import warnings

from src.util import crop_image, generate_color_chart, get_device_info, get_mask, get_mask_json, get_overlay, get_product_colors, load_image, remove_image_background

# Disable Warning generated by External Model
warnings.filterwarnings("ignore")

# Configure Web App
st.set_option("deprecation.showfileUploaderEncoding", False)
st.set_page_config(
    page_title="Find By Color",
    page_icon=os.path.join(".streamlit", "img", "icon.ico"),
    initial_sidebar_state="collapsed",
    layout="centered",
    menu_items={
        'Get Help': 'https://github.com/FindByColor/proof-of-concept#readme',
        'Report a bug': "https://github.com/FindByColor/proof-of-concept/issues/new",
        'About': get_device_info()
    }
)

# Apply CSS Overrides
css = open(os.path.join(".streamlit", "css", "style.css"), "r")
st.markdown("<style>{:s}</style>".format(css.read()), unsafe_allow_html=True)

# Output Logo
svg = open(os.path.join(".streamlit", "img", "logo.svg"), "r")
st.write(svg.read(), unsafe_allow_html=True)

# Generate UI Element for File Upload
uploaded_file = st.file_uploader("Upload Image ...", type=["jpg", "png"], label_visibility="hidden")

# Wait for File Upload
if uploaded_file is not None:
    # Start Loading Indicator
    with st.spinner(text="Processing Image..."):
        # STEP 1: Load Original Image
        original_image = load_image(uploaded_file)

        # STEP 2: Generate Image Mask
        mask = get_mask(original_image)

        # STEP 3: Generate Detected Product Image
        overlay = get_overlay(original_image, mask)

        # STEP 4: Remove Background from Image
        processed_image = remove_image_background(original_image, mask)

        # STEP 5: Trim Image to Remove Transparent Pixels
        cropped_image = crop_image(processed_image)

        # STEP 6: Process Colors from Clipped Image
        colors = get_product_colors(cropped_image)

        # STEP 7: Generate Color Chart
        product_color_chart = generate_color_chart(colors, cropped_image)
        
        # Generate Tabbed Interface
        tab1, tab2, tab3, tab4, tab5 = st.tabs(["Original", "Processed", "Steps", "Data", "Colors"])

        # Original Image Tab
        with tab1:
            st.image(original_image, caption="Original Product Image", use_column_width=True)

        # Processed Image Tab
        with tab2:
            st.image(processed_image, caption="Processed Product Image", use_column_width=True)

        # Steps Tab
        with tab3:
            col1, col2 = st.columns(2)
            with col1:
                st.image(original_image, caption="Original Product Image", use_column_width=True)
                st.image(mask * 255, caption="Detected Product Mask", use_column_width=True)

            with col2:
                st.image(overlay, caption="Detected Product Overlay", use_column_width=True)
                st.image(processed_image, caption="Processed Product Image", use_column_width=True)

        # Data Tab
        with tab4:
            st.subheader("Product Mask")
            st.dataframe(mask, use_container_width=True)

            # Download JSON Mapping of Pixel Data
            st.download_button(
                label="Download",
                data=get_mask_json(mask),
                file_name="mask.json",
                mime="application/json",
                key="download-mask-json"
            )

        # Colors Tab
        with tab5:
            st.subheader("Color Usage")
            st.image(product_color_chart, use_column_width=True)

            st.dataframe(colors, use_container_width=True)

            # Download JSON Mapping of Pixel Data
            st.download_button(
                label="Download",
                data=colors.to_json(),
                file_name="color.json",
                mime="application/json",
                key="download-color-json"
            )