#!/usr/bin/python

"""CLI for Find By Color Proof of Concept"""

import argparse
import os
import warnings

from datetime import datetime 
from pathlib import Path
from src.config import COLOR_LIMIT, COLOR_TOLERANCE, MAX_IMAGE_SIZE
from src.util import extract_color, ranged_int, max_image_size

# Disable Warning generated by External Model
warnings.filterwarnings("ignore")

# Setup CLI Parser
parser = argparse.ArgumentParser(prog='fbc-process-batch', description="Batch Color Extractor", epilog="Find By Color - Batch Color Extractor", formatter_class=argparse.ArgumentDefaultsHelpFormatter)
parser.add_argument('-l', '--limit', type=ranged_int(1, 12), metavar='\b', default=COLOR_LIMIT, help="Limit of Extracted Colors [1-12]")
parser.add_argument('-m', '--max-size', type=max_image_size(512, 1024), metavar='\b', default=MAX_IMAGE_SIZE, help="Max Image Size before Resize [512-1024]")
parser.add_argument('-t', '--tolerance', type=ranged_int(0, 100), metavar='\b', default=COLOR_TOLERANCE, help="Threshold to Group Related Colors [0-100]")

args = parser.parse_args()
config = vars(args)

# Run Function with Configs
if __name__ == '__main__':
    start_time = datetime.now() 
    input = os.path.abspath('./data/input')
    output = os.path.abspath('./data/output')

    # Loop through data/input
    for subdir, dirs, files in os.walk(input):
        for file in files:
            if file.endswith(('.jpg', '.png')):
                source_image = os.path.join(subdir, file)
                output_path = os.path.splitext(source_image)[0]
                output_path = output_path.replace(input, output)

                config["filename"] = Path(source_image)
                config["dest"] = Path(output_path)
                
                extract_color(config)

    time_elapsed = datetime.now() - start_time
    print('Time elapsed (hh:mm:ss.ms) {}'.format(time_elapsed))