#!/usr/bin/python

"""CLI for Find By Color Proof of Concept"""

import argparse
import numpy as np
import os
import pathlib
import warnings

from PIL import Image 

from src.config import COLOR_LIMIT, COLOR_TOLERANCE, MAX_IMAGE_SIZE
from src.util import crop_image, generate_color_chart, get_mask, get_mask_json, get_overlay, get_product_colors, load_image, remove_image_background

# Disable Warning generated by External Model
warnings.filterwarnings("ignore")

def extract_color(config):
    # Make sure file exists before processing
    if not os.path.exists(config["filename"].resolve()):
        return print("❌ Unable to locate file: {}".format(config["filename"].resolve()))
    
    # Make directory if it does not exist
    if not os.path.exists(config["dest"].resolve()):
        os.makedirs(config["dest"].resolve())

    # STEP 1: Load Original Image
    original_image = load_image(config["filename"].resolve())
    image = Image.fromarray(original_image.astype(np.uint8))
    image.save(os.path.join(config["dest"].resolve(), "original-image.png"))
    image.close()

    # STEP 2: Generate Mask Image & JSON
    mask = get_mask(original_image)
    image = Image.fromarray((mask * 255).astype(np.uint8))
    image.save(os.path.join(config["dest"].resolve(), "mask.png"))
    image.close()

    with open(os.path.join(config["dest"].resolve(), "mask.json"), "w") as outfile:
        outfile.write(get_mask_json(mask))

    # STEP 3: Generate Detected Product Image
    overlay = get_overlay(original_image, mask)
    image = Image.fromarray(overlay.astype(np.uint8))
    image.save(os.path.join(config["dest"].resolve(), "overlay.png"))
    image.close()

    # STEP 4: Remove Background from Image
    processed_image = remove_image_background(original_image, mask)
    image = Image.fromarray(processed_image.astype(np.uint8))
    image.save(os.path.join(config["dest"].resolve(), "processed-image.png"))
    image.close()

    # STEP 5: Trim Image to Remove Transparent Pixels
    cropped_image = crop_image(processed_image)
    image = cropped_image.copy()
    image.save(os.path.join(config["dest"].resolve(), "cropped-image.png"))
    image.close()

    # STEP 6: Process Colors from Clipped Image for JSON
    colors = get_product_colors(cropped_image)
    with open(os.path.join(config["dest"].resolve(), "colors.json"), "w") as outfile:
        outfile.write(colors.to_json())

    # STEP 7: Generate Color Chart
    product_color_chart = generate_color_chart(colors, cropped_image)
    product_color_chart.save(os.path.join(config["dest"].resolve(), "product-color-chart.png"))
    product_color_chart.close()

    return print("✅ Generated Assets: {} => {}".format(os.path.relpath(config["filename"].resolve()), os.path.relpath(config["dest"].resolve())))

def ranged_int(min_value, max_value):
    def check_valid(arg: str):
        try:
            val = int(arg)
        except ValueError:
            raise argparse.ArgumentTypeError(f'must be a valid `int`')
        if val < min_value or val > max_value:
            raise argparse.ArgumentTypeError(f'must be within [{min_value}, {max_value}]')
        return val

    return check_valid

def max_image_size(min_value, max_value):
    def check_valid(arg: str):
        try:
            val = int(arg)
        except ValueError:
            raise argparse.ArgumentTypeError(f'must be a valid `int`')
        if val < min_value or val > max_value:
            raise argparse.ArgumentTypeError(f'must be within [{min_value}, {max_value}]')
        if val%32:
            raise argparse.ArgumentTypeError(f'must be divisible by 32')
        return val

    return check_valid

# Setup CLI Parser
parser = argparse.ArgumentParser(prog='fbc-process-image', description="Color Extractor", epilog="Find By Color Color Extractor", formatter_class=argparse.ArgumentDefaultsHelpFormatter)
parser.add_argument('filename', type=pathlib.Path, help="Source location")
parser.add_argument('-d', '--dest', type=pathlib.Path, metavar='\b', help="Destination location", required=True)
parser.add_argument('-l', '--limit', type=ranged_int(1, 12), metavar='\b', default=COLOR_LIMIT, help="Limit of Extracted Colors [1-12]")
parser.add_argument('-m', '--max-size', type=max_image_size(512, 1024), metavar='\b', default=MAX_IMAGE_SIZE, help="Max Image Size before Resize [512-1024]")
parser.add_argument('-t', '--tolerance', type=ranged_int(0, 100), metavar='\b', default=COLOR_TOLERANCE, help="Threshold to Group Related Colors [0-100]")

args = parser.parse_args()
config = vars(args)

# Run Function with Configs
if __name__ == '__main__':
    extract_color(config)