#!/usr/bin/python

"""CLI for Find By Color Proof of Concept"""

import argparse
import pathlib
import warnings

from src.config import COLOR_LIMIT, COLOR_TOLERANCE, MAX_IMAGE_SIZE
from src.util import extract_color, ranged_int, max_image_size

# Disable Warning generated by External Model
warnings.filterwarnings("ignore")

# Setup CLI Parser
parser = argparse.ArgumentParser(prog='fbc-process-image', description="Color Extractor", epilog="Find By Color - Color Extractor", formatter_class=argparse.ArgumentDefaultsHelpFormatter)
parser.add_argument('filename', type=pathlib.Path, help="Source location")
parser.add_argument('-d', '--dest', type=pathlib.Path, metavar='\b', help="Destination location", required=True)
parser.add_argument('-l', '--limit', type=ranged_int(1, 12), metavar='\b', default=COLOR_LIMIT, help="Limit of Extracted Colors [1-12]")
parser.add_argument('-m', '--max-size', type=max_image_size(512, 1024), metavar='\b', default=MAX_IMAGE_SIZE, help="Max Image Size before Resize [512-1024]")
parser.add_argument('-t', '--tolerance', type=ranged_int(0, 100), metavar='\b', default=COLOR_TOLERANCE, help="Threshold to Group Related Colors [0-100]")

args = parser.parse_args()
config = vars(args)

# Run Function with Configs
if __name__ == '__main__':
    extract_color(config)